### ISSUE TITLE
Can we use customized genome ? 

### ISSUE THREAD

**Issue by LoneKnightz** [ajlabuc/meCLIP#1]
Hi, 

Thanks for providing this powerful tools for m6a. 

I have checked your document and it seems we can only download the genome for this pipeline. 

May I ask can I use our own genome and gif?  

Should I just change the url to our genome path in manual-reference-genome.yml ? 

Or is there any way to do that? 

Thanks

**Comment by NanoCoreUSA** [comment]
Hi @LoneKnightz,

Apologies for the late reply, I must have missed the notification. 

Yes, I've recently made some updates to the pipeline and you should be able to input custom genomes using the 'manual-reference-genome.yml' file and then executing the command below.

`snakemake --snakefile workflow/rules/genome-download.smk --cores N`

Please let me know how it goes, I haven't gotten a chance to test this feature much so would be curious how it works.

**Comment by LoneKnightz** [comment]
Thanks!
