### ISSUE TITLE
May I ask how to config if the adapter is not listed in the library ?

### ISSUE THREAD

**Issue by LoneKnightz** [ajlabuc/meCLIP#2]
Hi, 

I am sorry to bother you again. 

I have checked the document/Readme and it mentioned we should give the adapter sequence and name from eCLIP library. 

But the data I have now is using TruSeq RNA adapter : AGATCGGAAGAGCACACGTCTGAACTCCAGTCA.  ssDNA adapter: NNNNNNNNNNAGATCGGAAGAGCGTCGTGT 

May I ask how should I modify the config files to make it work? 

Or can I use cutadapt myself and then feed into the pipeline ?

Thanks

**Comment by NanoCoreUSA** [comment]
Hi @LoneKnightz 

The pipeline automatically handles Illumina TruSeq adapters as is, I would just give it a go and as long you summary report shows the adapters were removed successfully you should be good to go.

**Comment by LoneKnightz** [comment]
Thanks!
